name: "parse-refname"
description: "Parse a tag"
inputs:
  ref:
    description: "The refname."
    required: false
  default-ref-type:
    description: "Ref type applied for shorthand refnames."
    required: false
    default: "tags"
outputs:
  ref-type:
    description: "The type/namespace of the ref."
  ref-name:
    description: "The ref with the 'refs/<type>/' prefix stripped."
runs:
  using: "node16"
  main: "dist/index.js"
